server:
  port: 10000
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10     # 服务刷新时间配置，每隔这个时间会主动心跳一次 ，默认30s
    lease-expiration-duration-in-seconds: 30  # 服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除, 默认90s, 注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://172.18.1.133:10000/eureka/
    fetch-registry: false
    register-with-eureka: false
spring:
  application:
    name: EurekaServer


